appdir: "{{ ansible_user_dir }}/spring"
branch: "devops"
appuser: "{{ansible_user_id}}"
appgroup: "{{ansible_user_gid}}"
app_port: 8080
backend_server_url: "http://192.168.56.4:8080"
app1:
  target:  http://192.168.56.16
app:
  env:
    server.port: "{{app_port}}"
    spring.datasource.username: appuser
    spring.datasource.password: apppassword
    spring.datasource.url: jdbc:postgresql://localdb-2:5432/appdb